#!/usr/bin/python3
import sys

if len(sys.argv) < 3:
    sys.exit()

base = float(sys.argv[1])
max_n = int(float(sys.argv[2]))

print(f"--- {base} の累乗テーブル ---")

for i in range(1, max_n + 1):
    val = base ** i
    print(f"{base} ^ {i} = {val}")
